version: "3"

services:
  mdah:
    container_name: mdah
    image: "openjdk:19-slim"
    restart: unless-stopped
    # hostname ending with `localhost` to avoid SNI check
    hostname: mdahlocalhost
    user: "${COMPOSE_UID}:${COMPOSE_GID}"
    command:
      [
        "bash",
        "-c",
        "java -Dfile-level=off -Dstdout-level=info -jar /mdah/data/mdah-client.jar --settings /mdah/config/settings.yaml --cache /mdah/cache/ --database /mdah/data"
      ]
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "2"
    ports:
      - "44300:44300"
    volumes:
      - ./mdah/config:/mdah/config
      - ./mdah/data:/mdah/data
      - ./mdah/cache:/mdah/cache

  prometheus:
    container_name: prometheus_mdah
    image: prom/prometheus:v2.34.0
    restart: unless-stopped
    user: "root"
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/config/:/etc/prometheus/
      - ./prometheus/data:/prometheus/
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "2"

  grafana:
    container_name: grafana_mdah
    image: grafana/grafana:8.4.3
    restart: unless-stopped
    user: "root"
    ports:
      - 3000:3000
    volumes:
      - ./grafana/config:/etc/grafana/
      - ./grafana/data:/var/lib/grafana/
    environment:
      GF_INSTALL_PLUGINS: "grafana-worldmap-panel"
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "2"
