global:
  scrape_interval: 20s
  scrape_timeout: 10s

scrape_configs:
  - job_name: "mangadex-at-home"
    scheme: https
    tls_config:
      insecure_skip_verify: true
    metrics_path: /prometheus
    static_configs:
      - targets: ["mdahlocalhost:44300"]
        labels:
          instance: "837"
