{
 "title": "MangaDex@Home - Personal client dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "itvl",
    "label": "Resolution",
    "query": "2m,3m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Combined overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "description": "*Warning:* CPU load can be a bit of a deceiving metric\n\nBest I can say is read the [wikipedia article](https://en.wikipedia.org/wiki/Load_(computing)#Interpretation)",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "CPU load (1m)" }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "description": "Amount *used* by the JVM\n\nIt might have requested more from the system (*commited*), but this is the amount it actually is using out of it",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(jvm_memory_used_bytes)",
     "legendFormat": "Used",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(jvm_memory_committed_bytes)",
     "legendFormat": "Committed",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "timeseries",
   "description": "Cache size allocated, does not include metadata or other overhead, but does somewhat account for block sizes.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(cache_used_bytes)",
     "legendFormat": "Used",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(cache_max_bytes)",
     "legendFormat": "Max",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Outgoing bandwidth  [$itvl]",
   "type": "timeseries",
   "description": "This is the mean outgoing network speed reported, by blocks of [$itvl].",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(rate(client_sent_bytes_total[$itvl])) * 8",
     "legendFormat": "Actual",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Current uptime of client process",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_uptime_seconds", "legendFormat": "Version: {{ version }}" }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "description": "This is the number of threads the JVM is currently using\n\nShould generally be around `50 + <requests per second>`",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(jvm_threads_live_threads)",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "FDs",
   "type": "stat",
   "description": "Files currently opened\n\nShould generally be around `100 + <images per second>`",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(process_files_open_files)",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Heap",
   "type": "stat",
   "description": "This can be seen as the \"live\" memory of the JVM\n\nIn a healthy situation, it should fluctuate up and down regularly (as more data is used, then old one is released)",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\"})",
     "legendFormat": "JVM",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Non-heap",
   "type": "stat",
   "description": "This can be seen as the memory used by the JVM for critical use\n\nIt should generally be mostly static and not vary much",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Time lost to GC",
   "type": "stat",
   "description": "This is the percentage of time that your client spends freeing up memory, specifically when this process requires your application to completely pause.\n\nIf this is at 50%, it would mean that out of every 1 second that passes, your application is paused for 500ms of it. It should never be higher than a percent or so.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(rate(jvm_gc_pause_seconds_sum[$itvl])) / sum(rate(process_uptime_seconds[$itvl]))",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Served images",
   "type": "stat",
   "description": "Total number of requests successfully served over timerange selected",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(increase(http_server_request_latency_seconds_count{status=~\"2..\", path=~\"(.*)data/{chapterHash}/{fileName}\"}[$__range]))",
     "legendFormat": "Over timerange",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(increase(http_server_request_latency_seconds_count{status=~\"2..\", path=~\"(.*)data/{chapterHash}/{fileName}\"}[1y]))",
     "legendFormat": "Total (1y)",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Sent data",
   "type": "stat",
   "description": "Total bytes sent over timerange currently selected",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(increase(client_sent_bytes_total[$__range]))",
     "legendFormat": "Over timerange",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(increase(client_sent_bytes_total[1y]))",
     "legendFormat": "Total (1y)",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  { "title": "Mangadex", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Requests served [$itvl]",
   "type": "graph",
   "gridPos": { "h": 14, "w": 9, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_request_latency_seconds_count{path=~\"(.*)data/{chapterHash}/{fileName}\", status=~\"(4|5)..\"}[$itvl]))",
     "legendFormat": "Request - FAIL"
    },
    {
     "expr": "sum(rate(http_server_request_latency_seconds_count{path=~\"(.*)data/{chapterHash}/{fileName}\", status=~\"2..\"}[$itvl])) by (cache)",
     "legendFormat": "Request - {{ cache }}"
    },
    {
     "expr": "sum(rate(http_server_request_latency_seconds_sum{path=~\"(.*)data/{chapterHash}/{fileName}\", status=~\"2..\"}[$itvl]) / rate(http_server_request_latency_seconds_count{path=~\"(.*)data/{chapterHash}/{fileName}\", status=~\"2..\"}[$itvl])) by (cache)",
     "legendFormat": "Mean response time - {{ cache }}"
    }
   ]
  },
  {
   "title": "Cache spread [$itvl]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 13 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_request_latency_seconds_count{path=~\"(.*)data/{chapterHash}/{fileName}\"}[$itvl])) by (cache)",
     "legendFormat": "{{ cache }}"
    }
   ]
  },
  {
   "title": "Upstream status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(resilience4j_circuitbreaker_state{name=\"upstream\", state!=\"closed\"})",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Avg hitrate over timerange",
   "type": "stat",
   "description": "Average cache hitrate of the current timerange\n\nSplits timerange in blocks of [$itvl], and averages their averages",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_latency_seconds_count{path=~\"(.*)data/{chapterHash}/{fileName}\", cache=\"HIT\"}[$itvl])) / sum(rate(http_server_request_latency_seconds_count{path=~\"(.*)data/{chapterHash}/{fileName}\"}[$itvl]))"
    }
   ]
  },
  {
   "title": "Downloads from upstream [$itvl]",
   "type": "graph",
   "description": "This panel displays stats about upstream fetches\n\nTTFB is the time taken by upstream to start replying\n\nStatuses can be:\n- **successful** - executed with success\n- **failed** - executed but failed for some reason\n- **ignored** - to avoid spamming upstream when it's dead or suffering, the client avoids calling it many times in a row if they keep failing",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 17 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(resilience4j_circuitbreaker_calls_seconds_count{name=\"upstream\"}[$itvl])) by (kind)",
     "legendFormat": "{{ kind }}"
    },
    {
     "expr": "avg(rate(resilience4j_circuitbreaker_calls_seconds_sum[$itvl])) / avg(rate(resilience4j_circuitbreaker_calls_seconds_count[$itvl]))",
     "legendFormat": "TTFB"
    }
   ]
  },
  {
   "title": "Cache latency [$itvl]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(avg_over_time(cache_lookup_seconds[$itvl])) by (quantile)",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  { "title": "GeoIP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Origin of requests over timerange",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 15, "w": 11, "x": 0, "y": 28 },
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(requests_country_counts_total[$__range])) by (country)",
     "legendFormat": "{{ country }}"
    }
   ]
  },
  {
   "title": "Country spread [$itvl]",
   "type": "graph",
   "gridPos": { "h": 15, "w": 13, "x": 11, "y": 28 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum(rate(requests_country_counts_total[$itvl])) by (country))",
     "legendFormat": "{{ country }}"
    }
   ]
  }
 ]
}