{
 "title": "Client #837",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "itvl",
    "label": "Resolution",
    "query": "2m,3m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "target", "label": "Target", "query": "837" }
  ]
 },
 "panels": [
  {
   "title": "Version & Uptime",
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{instance = \"${target}\"}",
     "legendFormat": "Targetting #{{ instance }} on v{{ version }}"
    }
   ]
  },
  { "title": "Cache Server — Front", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Requests statuses [$itvl]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_latency_seconds_count{instance = \"${target}\", path=~\"(.*)(data|data-saver)/{chapterHash}/{fileName}\", status=~\"2..\", cache=\"HIT\"}[$itvl]))",
     "legendFormat": "Success (cached)"
    },
    {
     "expr": "sum(rate(http_server_request_latency_seconds_count{instance = \"${target}\", path=~\"(.*)(data|data-saver)/{chapterHash}/{fileName}\", status=~\"2..\", cache=\"MISS\"}[$itvl]))",
     "legendFormat": "Success (forwarded)"
    },
    {
     "expr": "sum(rate(http_server_request_latency_seconds_count{instance = \"${target}\", path=~\"(.*)(data|data-saver)/{chapterHash}/{fileName}\", status=~\"(4)..\"}[$itvl]))",
     "legendFormat": "Client Error"
    },
    {
     "expr": "sum(rate(http_server_request_latency_seconds_count{instance = \"${target}\", path=~\"(.*)data/{chapterHash}/{fileName}\", status=~\"(5)..\"}[$itvl]))",
     "legendFormat": "Server Error"
    },
    {
     "expr": "sum(rate(http_server_request_latency_seconds_count{instance = \"${target}\", path=~\"(.*)(data|data-saver)/{chapterHash}/{fileName}\", status=~\"(1|3)..\"}[$itvl]))",
     "legendFormat": "Unknown Error"
    },
    {
     "expr": "sum(rate(http_server_request_latency_seconds_count{instance = \"${target}\", path=~\"(.*)(data|data-saver)/{chapterHash}/{fileName}\"}[$itvl]))",
     "legendFormat": "Total (data, data-saver)"
    }
   ]
  },
  {
   "title": "Requests mean latency [$itvl]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_latency_seconds_sum{instance = \"${target}\", path=~\"(.*)data/{chapterHash}/{fileName}\", status=~\"2..\", cache=\"HIT\"}[$itvl]) / rate(http_server_request_latency_seconds_count{instance = \"${target}\", path=~\"(.*)data/{chapterHash}/{fileName}\", status=~\"2..\", cache=\"HIT\"}[$itvl]))",
     "legendFormat": "Success (cached)"
    },
    {
     "expr": "sum(rate(http_server_request_latency_seconds_sum{instance = \"${target}\", path=~\"(.*)data/{chapterHash}/{fileName}\", status=~\"2..\", cache=\"MISS\"}[$itvl]) / rate(http_server_request_latency_seconds_count{instance = \"${target}\", path=~\"(.*)data/{chapterHash}/{fileName}\", status=~\"2..\", cache=\"MISS\"}[$itvl]))",
     "legendFormat": "Success (forwarded)"
    },
    {
     "expr": "sum(rate(http_server_request_latency_seconds_sum{instance = \"${target}\", path=~\"(.*)data-saver/{chapterHash}/{fileName}\", status=~\"2..\", cache=\"HIT\"}[$itvl]) / rate(http_server_request_latency_seconds_count{instance = \"${target}\", path=~\"(.*)data-saver/{chapterHash}/{fileName}\", status=~\"2..\", cache=\"HIT\"}[$itvl]))",
     "legendFormat": "Success (cached, data-saver)"
    },
    {
     "expr": "sum(rate(http_server_request_latency_seconds_sum{instance = \"${target}\", path=~\"(.*)data-saver/{chapterHash}/{fileName}\", status=~\"2..\", cache=\"MISS\"}[$itvl]) / rate(http_server_request_latency_seconds_count{instance = \"${target}\", path=~\"(.*)data-saver/{chapterHash}/{fileName}\", status=~\"2..\", cache=\"MISS\"}[$itvl]))",
     "legendFormat": "Success (forwarded, data-saver)"
    },
    {
     "expr": "sum(rate(http_server_request_latency_seconds_sum{instance = \"${target}\", path=~\"(.*)data/{chapterHash}/{fileName}\", status!~\"2..\", cache=\"MISS\"}[$itvl]) / rate(http_server_request_latency_seconds_count{instance = \"${target}\", path=~\"(.*)data/{chapterHash}/{fileName}\", status!~\"2..\", cache=\"MISS\"}[$itvl]))",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "Cached requests [$itvl]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_latency_seconds_count{instance = \"${target}\", path=~\"(.*)(data|data-saver)/{chapterHash}/{fileName}\", cache=\"HIT\", status=~\"2..\"}[$itvl])) / sum(rate(http_server_request_latency_seconds_count{instance = \"${target}\", path=~\"(.*)(data|data-saver)/{chapterHash}/{fileName}\", status=~\"2..\"}[$itvl])) "
    }
   ]
  },
  {
   "title": "Forwarded requests [$itvl]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_latency_seconds_count{instance = \"${target}\", path=~\"(.*)(data|data-saver)/{chapterHash}/{fileName}\", cache=\"MISS\", status=~\"2..\"}[$itvl])) / sum(rate(http_server_request_latency_seconds_count{instance = \"${target}\", path=~\"(.*)(data|data-saver)/{chapterHash}/{fileName}\", status=~\"2..\"}[$itvl])) "
    }
   ]
  },
  {
   "title": "Requests cache breakdown [$itvl]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_latency_seconds_count{instance = \"${target}\", path=~\"(.*)(data|data-saver)/{chapterHash}/{fileName}\", cache=\"MISS\"}[$itvl]))",
     "legendFormat": "Forwarded"
    },
    {
     "expr": "sum(rate(http_server_request_latency_seconds_count{instance = \"${target}\", path=~\"(.*)(data|data-saver)/{chapterHash}/{fileName}\", cache=\"HIT\"}[$itvl]))",
     "legendFormat": "Cached"
    }
   ]
  },
  {
   "title": "Outbound Speed [$itvl]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(client_sent_bytes_total{instance = \"${target}\"}[$itvl])) * 8",
     "legendFormat": "Traffic Out"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(increase(http_server_request_latency_seconds_count{instance = \"${target}\", status=~\"2..\", path=~\"(.*)(data|data-saver)/{chapterHash}/{fileName}\"}[$__range]))",
     "legendFormat": "Timerange",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(increase(http_server_request_latency_seconds_count{instance = \"${target}\", status=~\"2..\", path=~\"(.*)(data|data-saver)/{chapterHash}/{fileName}\"}[1y]))",
     "legendFormat": "1 year",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Sent Data",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(increase(client_sent_bytes_total{instance = \"${target}\"}[$__range]))",
     "legendFormat": "Timerange",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(increase(client_sent_bytes_total{instance = \"${target}\"}[1y]))",
     "legendFormat": "1 year",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  { "title": "Cache Server — Back", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Upstream Calls & Status [$itvl]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(resilience4j_circuitbreaker_calls_seconds_count{instance = \"${target}\", name=\"upstream\", kind=\"failed\"}[$itvl]))",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(rate(resilience4j_circuitbreaker_calls_seconds_count{instance = \"${target}\", name=\"upstream\", kind=\"ignored\"}[$itvl]))",
     "legendFormat": "Ignored"
    },
    {
     "expr": "sum(rate(resilience4j_circuitbreaker_calls_seconds_count{instance = \"${target}\", name=\"upstream\", kind=\"successful\"}[$itvl]))",
     "legendFormat": "Success"
    },
    {
     "expr": "1 - sum(resilience4j_circuitbreaker_state{instance = \"${target}\", name=\"upstream\", state!=\"closed\"})",
     "legendFormat": "Upstream Status"
    }
   ]
  },
  {
   "title": "Upstream Latency [$itvl]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(resilience4j_circuitbreaker_calls_seconds_sum{instance = \"${target}\"}[$itvl])) / avg(rate(resilience4j_circuitbreaker_calls_seconds_count{instance = \"${target}\"}[$itvl]))",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Mean cache response time [$itvl]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(cache_lookup_seconds{instance = \"${target}\"}[$itvl]))"
    }
   ]
  },
  {
   "title": "Cache latency [$itvl]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(avg_over_time(cache_lookup_seconds{instance = \"${target}\"}[$itvl])) by (quantile)",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Highest cache response time [$itvl]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(cache_lookup_seconds{instance = \"${target}\", quantile=\"0.99\"}[$itvl]))"
    }
   ]
  },
  { "title": "Cache Server — Host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Memory usage (client)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{instance = \"${target}\", area=\"heap\"})",
     "legendFormat": "Heap"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{instance = \"${target}\", area=\"nonheap\"})",
     "legendFormat": "Non Heap"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{instance = \"${target}\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{instance = \"${target}\"})",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "CPU usage (client)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_cpu_usage{instance = \"${target}\"}",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "sum(rate(jvm_gc_pause_seconds_sum{instance = \"${target}\"}[$itvl])) / sum(rate(process_uptime_seconds{instance = \"${target}\"}[$itvl]))",
     "legendFormat": "GC Time"
    }
   ]
  },
  {
   "title": "Active Threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(jvm_threads_live_threads{instance = \"${target}\"})",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Opened FDs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(process_files_open_files{instance = \"${target}\"})",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  { "title": "Cache Server — Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Origin of requests (worldmap)",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 14, "w": 14, "x": 0, "y": 52 },
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(requests_country_counts_total{instance = \"${target}\"}[$__range])) by (country)",
     "legendFormat": "{{ country }}"
    }
   ]
  },
  {
   "title": "Origin of requests (rqps)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 10, "x": 14, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(5, sum(rate(requests_country_counts_total{instance = \"${target}\"}[$itvl])) by (country))",
     "legendFormat": "{{ country }}"
    }
   ]
  },
  { "title": "Cache Server — Raw Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Requests by status, path, cache [$itvl]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_latency_seconds_count{instance = \"${target}\"}[$itvl])) by (status, path, cache)",
     "legendFormat": "{{ status }} [{{path}}] - {{ cache }}"
    }
   ]
  },
  {
   "title": "Requests by latency [$itvl]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_latency_seconds_sum{instance = \"${target}\"}[$itvl]) / rate(http_server_request_latency_seconds_count{instance = \"${target}\"}[$itvl])) by (status, path, cache)",
     "legendFormat": "{{ status}} [{{ path }}] - {{ cache }}"
    }
   ]
  },
  {
   "title": "Requests by path [$itvl]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_latency_seconds_count{instance = \"${target}\"}[$itvl])) by (path)",
     "legendFormat": "{{ path }} "
    }
   ]
  },
  {
   "title": "Requests by status [$itvl]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_latency_seconds_count{instance = \"${target}\"}[$itvl])) by (status)",
     "legendFormat": "{{ status }} "
    }
   ]
  },
  {
   "title": "Total requests [$itvl]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_latency_seconds_count{instance = \"${target}\"}[$itvl]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Current Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_latency_seconds_count{instance = \"${target}\"}[$itvl]))"
    }
   ]
  },
  {
   "title": "Circuit Breaker",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(resilience4j_circuitbreaker_state{instance = \"${target}\", name=\"upstream\"}) by (state)",
     "legendFormat": "{{ state }}"
    }
   ]
  }
 ]
}